### ISSUE TITLE
powerlogHelperdFix stopped working

### ISSUE THREAD

**Issue by paullvu** [opa334/powerlogHelperdFix#1]
powerlogHelperdFix used to work great when I first downloaded it on my IOS 13.5 iPhone 8 because I couldn't see my battery info in settings. But started to not work around a week ago, and I've looked to reddit for help. Some have told me to use choicy, and others system info. They said to use choicy by disabling tweak injection then run ldrestart, so I did. Nothing changed. Turns out ldrestart unjailbroke my phone so I had to rejailbreak. My unjailbroken state brought back the battery info, stopped battery drainage, and cooled down my phone from about 120°F to around 80°F. Felt a big difference. I took that opportunity to rejailbreak and redownload every tweak I had before and double check back in settings if my battery info had disappeared. But even just 1 tweak no matter what it was caused my battery info to disappear and phone started to heat up again.

I have system info as of right now, but it hasn't made any difference if any. The only useful information it's given me was battery capacity, battery health, and CPU temperature. I'm starting to wonder if I could fix my problem with powerHelperdFix, I don't have to worry about downloading anything else and it not working. I'm grasping at straws and don't know what to do.

**Comment by opa334** [comment]
Yeah nothing works atm except for editing the jetsam plist, the next Substrate update will fix this. Here is a link to the beta: https://github.com/checkra1n/BugTracker/issues/343#issuecomment-659273220

**Comment by opa334** [comment]
Substrate update is out now... Closing
